/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActifsRouteImport } from './routes/actifs'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComparablesRouteImport } from './routes/comparables'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as EnvoisRouteImport } from './routes/envois'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as MonProfilRouteImport } from './routes/mon-profil'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PartagerRouteImport } from './routes/partager'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SyntheseTokenRouteImport } from './routes/synthese.$token'
import { Route as ApiPublicBrevoEventsRouteImport } from './routes/api/public/brevo-events'
import { Route as ApiPublicCronAiscanTickRouteImport } from './routes/api/public/cron/aiscan-tick'
import { Route as ApiPublicCronCfnewsTickRouteImport } from './routes/api/public/cron/cfnews-tick'
import { Route as ApiPublicCronDailyRouteImport } from './routes/api/public/cron/daily'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron/daily-digest'
import { Route as ApiPublicCronEmailTickRouteImport } from './routes/api/public/cron/email-tick'
import { Route as ApiPublicCronMailscanTickRouteImport } from './routes/api/public/cron/mailscan-tick'
import { Route as ApiPublicCronMailsyncTickRouteImport } from './routes/api/public/cron/mailsync-tick'
import { Route as ApiPublicTIdRouteImport } from './routes/api/public/t/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActifsRoute = ActifsRouteImport.update({
  id: '/actifs',
  path: '/actifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparablesRoute = ComparablesRouteImport.update({
  id: '/comparables',
  path: '/comparables',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvoisRoute = EnvoisRouteImport.update({
  id: '/envois',
  path: '/envois',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const MonProfilRoute = MonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PartagerRoute = PartagerRouteImport.update({
  id: '/partager',
  path: '/partager',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntheseTokenRoute = SyntheseTokenRouteImport.update({
  id: '/synthese/$token',
  path: '/synthese/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrevoEventsRoute = ApiPublicBrevoEventsRouteImport.update({
  id: '/api/public/brevo-events',
  path: '/api/public/brevo-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAiscanTickRoute = ApiPublicCronAiscanTickRouteImport.update({
  id: '/api/public/cron/aiscan-tick',
  path: '/api/public/cron/aiscan-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCfnewsTickRoute = ApiPublicCronCfnewsTickRouteImport.update({
  id: '/api/public/cron/cfnews-tick',
  path: '/api/public/cron/cfnews-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyRoute = ApiPublicCronDailyRouteImport.update({
  id: '/api/public/cron/daily',
  path: '/api/public/cron/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEmailTickRoute = ApiPublicCronEmailTickRouteImport.update({
  id: '/api/public/cron/email-tick',
  path: '/api/public/cron/email-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMailscanTickRoute =
  ApiPublicCronMailscanTickRouteImport.update({
    id: '/api/public/cron/mailscan-tick',
    path: '/api/public/cron/mailscan-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMailsyncTickRoute =
  ApiPublicCronMailsyncTickRouteImport.update({
    id: '/api/public/cron/mailsync-tick',
    path: '/api/public/cron/mailsync-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTIdRoute = ApiPublicTIdRouteImport.update({
  id: '/api/public/t/$id',
  path: '/api/public/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actifs': typeof ActifsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth': typeof AuthRoute
  '/comparables': typeof ComparablesRoute
  '/contacts': typeof ContactsRoute
  '/dossiers': typeof DossiersRoute
  '/envois': typeof EnvoisRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mon-profil': typeof MonProfilRoute
  '/parametres': typeof ParametresRoute
  '/partager': typeof PartagerRoute
  '/prospects': typeof ProspectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/validation': typeof ValidationRoute
  '/synthese/$token': typeof SyntheseTokenRoute
  '/api/public/brevo-events': typeof ApiPublicBrevoEventsRoute
  '/api/public/cron/aiscan-tick': typeof ApiPublicCronAiscanTickRoute
  '/api/public/cron/cfnews-tick': typeof ApiPublicCronCfnewsTickRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/email-tick': typeof ApiPublicCronEmailTickRoute
  '/api/public/cron/mailscan-tick': typeof ApiPublicCronMailscanTickRoute
  '/api/public/cron/mailsync-tick': typeof ApiPublicCronMailsyncTickRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actifs': typeof ActifsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth': typeof AuthRoute
  '/comparables': typeof ComparablesRoute
  '/contacts': typeof ContactsRoute
  '/dossiers': typeof DossiersRoute
  '/envois': typeof EnvoisRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mon-profil': typeof MonProfilRoute
  '/parametres': typeof ParametresRoute
  '/partager': typeof PartagerRoute
  '/prospects': typeof ProspectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/validation': typeof ValidationRoute
  '/synthese/$token': typeof SyntheseTokenRoute
  '/api/public/brevo-events': typeof ApiPublicBrevoEventsRoute
  '/api/public/cron/aiscan-tick': typeof ApiPublicCronAiscanTickRoute
  '/api/public/cron/cfnews-tick': typeof ApiPublicCronCfnewsTickRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/email-tick': typeof ApiPublicCronEmailTickRoute
  '/api/public/cron/mailscan-tick': typeof ApiPublicCronMailscanTickRoute
  '/api/public/cron/mailsync-tick': typeof ApiPublicCronMailsyncTickRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actifs': typeof ActifsRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth': typeof AuthRoute
  '/comparables': typeof ComparablesRoute
  '/contacts': typeof ContactsRoute
  '/dossiers': typeof DossiersRoute
  '/envois': typeof EnvoisRoute
  '/investisseurs': typeof InvestisseursRoute
  '/mon-profil': typeof MonProfilRoute
  '/parametres': typeof ParametresRoute
  '/partager': typeof PartagerRoute
  '/prospects': typeof ProspectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/validation': typeof ValidationRoute
  '/synthese/$token': typeof SyntheseTokenRoute
  '/api/public/brevo-events': typeof ApiPublicBrevoEventsRoute
  '/api/public/cron/aiscan-tick': typeof ApiPublicCronAiscanTickRoute
  '/api/public/cron/cfnews-tick': typeof ApiPublicCronCfnewsTickRoute
  '/api/public/cron/daily': typeof ApiPublicCronDailyRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/email-tick': typeof ApiPublicCronEmailTickRoute
  '/api/public/cron/mailscan-tick': typeof ApiPublicCronMailscanTickRoute
  '/api/public/cron/mailsync-tick': typeof ApiPublicCronMailsyncTickRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actifs'
    | '/arbitrage'
    | '/auth'
    | '/comparables'
    | '/contacts'
    | '/dossiers'
    | '/envois'
    | '/investisseurs'
    | '/mon-profil'
    | '/parametres'
    | '/partager'
    | '/prospects'
    | '/sitemap.xml'
    | '/validation'
    | '/synthese/$token'
    | '/api/public/brevo-events'
    | '/api/public/cron/aiscan-tick'
    | '/api/public/cron/cfnews-tick'
    | '/api/public/cron/daily'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/email-tick'
    | '/api/public/cron/mailscan-tick'
    | '/api/public/cron/mailsync-tick'
    | '/api/public/t/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actifs'
    | '/arbitrage'
    | '/auth'
    | '/comparables'
    | '/contacts'
    | '/dossiers'
    | '/envois'
    | '/investisseurs'
    | '/mon-profil'
    | '/parametres'
    | '/partager'
    | '/prospects'
    | '/sitemap.xml'
    | '/validation'
    | '/synthese/$token'
    | '/api/public/brevo-events'
    | '/api/public/cron/aiscan-tick'
    | '/api/public/cron/cfnews-tick'
    | '/api/public/cron/daily'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/email-tick'
    | '/api/public/cron/mailscan-tick'
    | '/api/public/cron/mailsync-tick'
    | '/api/public/t/$id'
  id:
    | '__root__'
    | '/'
    | '/actifs'
    | '/arbitrage'
    | '/auth'
    | '/comparables'
    | '/contacts'
    | '/dossiers'
    | '/envois'
    | '/investisseurs'
    | '/mon-profil'
    | '/parametres'
    | '/partager'
    | '/prospects'
    | '/sitemap.xml'
    | '/validation'
    | '/synthese/$token'
    | '/api/public/brevo-events'
    | '/api/public/cron/aiscan-tick'
    | '/api/public/cron/cfnews-tick'
    | '/api/public/cron/daily'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/email-tick'
    | '/api/public/cron/mailscan-tick'
    | '/api/public/cron/mailsync-tick'
    | '/api/public/t/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActifsRoute: typeof ActifsRoute
  ArbitrageRoute: typeof ArbitrageRoute
  AuthRoute: typeof AuthRoute
  ComparablesRoute: typeof ComparablesRoute
  ContactsRoute: typeof ContactsRoute
  DossiersRoute: typeof DossiersRoute
  EnvoisRoute: typeof EnvoisRoute
  InvestisseursRoute: typeof InvestisseursRoute
  MonProfilRoute: typeof MonProfilRoute
  ParametresRoute: typeof ParametresRoute
  PartagerRoute: typeof PartagerRoute
  ProspectsRoute: typeof ProspectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ValidationRoute: typeof ValidationRoute
  SyntheseTokenRoute: typeof SyntheseTokenRoute
  ApiPublicBrevoEventsRoute: typeof ApiPublicBrevoEventsRoute
  ApiPublicCronAiscanTickRoute: typeof ApiPublicCronAiscanTickRoute
  ApiPublicCronCfnewsTickRoute: typeof ApiPublicCronCfnewsTickRoute
  ApiPublicCronDailyRoute: typeof ApiPublicCronDailyRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  ApiPublicCronEmailTickRoute: typeof ApiPublicCronEmailTickRoute
  ApiPublicCronMailscanTickRoute: typeof ApiPublicCronMailscanTickRoute
  ApiPublicCronMailsyncTickRoute: typeof ApiPublicCronMailsyncTickRoute
  ApiPublicTIdRoute: typeof ApiPublicTIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actifs': {
      id: '/actifs'
      path: '/actifs'
      fullPath: '/actifs'
      preLoaderRoute: typeof ActifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparables': {
      id: '/comparables'
      path: '/comparables'
      fullPath: '/comparables'
      preLoaderRoute: typeof ComparablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envois': {
      id: '/envois'
      path: '/envois'
      fullPath: '/envois'
      preLoaderRoute: typeof EnvoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-profil': {
      id: '/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof MonProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partager': {
      id: '/partager'
      path: '/partager'
      fullPath: '/partager'
      preLoaderRoute: typeof PartagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthese/$token': {
      id: '/synthese/$token'
      path: '/synthese/$token'
      fullPath: '/synthese/$token'
      preLoaderRoute: typeof SyntheseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brevo-events': {
      id: '/api/public/brevo-events'
      path: '/api/public/brevo-events'
      fullPath: '/api/public/brevo-events'
      preLoaderRoute: typeof ApiPublicBrevoEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/aiscan-tick': {
      id: '/api/public/cron/aiscan-tick'
      path: '/api/public/cron/aiscan-tick'
      fullPath: '/api/public/cron/aiscan-tick'
      preLoaderRoute: typeof ApiPublicCronAiscanTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cfnews-tick': {
      id: '/api/public/cron/cfnews-tick'
      path: '/api/public/cron/cfnews-tick'
      fullPath: '/api/public/cron/cfnews-tick'
      preLoaderRoute: typeof ApiPublicCronCfnewsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily': {
      id: '/api/public/cron/daily'
      path: '/api/public/cron/daily'
      fullPath: '/api/public/cron/daily'
      preLoaderRoute: typeof ApiPublicCronDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/email-tick': {
      id: '/api/public/cron/email-tick'
      path: '/api/public/cron/email-tick'
      fullPath: '/api/public/cron/email-tick'
      preLoaderRoute: typeof ApiPublicCronEmailTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mailscan-tick': {
      id: '/api/public/cron/mailscan-tick'
      path: '/api/public/cron/mailscan-tick'
      fullPath: '/api/public/cron/mailscan-tick'
      preLoaderRoute: typeof ApiPublicCronMailscanTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mailsync-tick': {
      id: '/api/public/cron/mailsync-tick'
      path: '/api/public/cron/mailsync-tick'
      fullPath: '/api/public/cron/mailsync-tick'
      preLoaderRoute: typeof ApiPublicCronMailsyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/$id': {
      id: '/api/public/t/$id'
      path: '/api/public/t/$id'
      fullPath: '/api/public/t/$id'
      preLoaderRoute: typeof ApiPublicTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActifsRoute: ActifsRoute,
  ArbitrageRoute: ArbitrageRoute,
  AuthRoute: AuthRoute,
  ComparablesRoute: ComparablesRoute,
  ContactsRoute: ContactsRoute,
  DossiersRoute: DossiersRoute,
  EnvoisRoute: EnvoisRoute,
  InvestisseursRoute: InvestisseursRoute,
  MonProfilRoute: MonProfilRoute,
  ParametresRoute: ParametresRoute,
  PartagerRoute: PartagerRoute,
  ProspectsRoute: ProspectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ValidationRoute: ValidationRoute,
  SyntheseTokenRoute: SyntheseTokenRoute,
  ApiPublicBrevoEventsRoute: ApiPublicBrevoEventsRoute,
  ApiPublicCronAiscanTickRoute: ApiPublicCronAiscanTickRoute,
  ApiPublicCronCfnewsTickRoute: ApiPublicCronCfnewsTickRoute,
  ApiPublicCronDailyRoute: ApiPublicCronDailyRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  ApiPublicCronEmailTickRoute: ApiPublicCronEmailTickRoute,
  ApiPublicCronMailscanTickRoute: ApiPublicCronMailscanTickRoute,
  ApiPublicCronMailsyncTickRoute: ApiPublicCronMailsyncTickRoute,
  ApiPublicTIdRoute: ApiPublicTIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
